# =============================================================================
# EXAMPLE SECRETS - DO NOT COMMIT ACTUAL VALUES TO GIT
# =============================================================================
# This file shows the structure of all secrets required for the application.
# Create these secrets in your deployment namespace before or after running
# the template.
#
# Option 1: Using kubectl
# ------------------------
# kubectl create secret generic llama-stack-secrets \
#   --from-literal=VLLM_API_KEY=<your-vllm-api-key> \
#   --from-literal=OPENAI_API_KEY=<your-openai-api-key> \
#   -n <your-namespace>
#
# kubectl create secret generic platform-credentials \
#   --from-literal=GITHUB_TOKEN=<your-github-pat> \
#   --from-literal=WEBHOOK_SECRET=<your-webhook-secret> \
#   --from-literal=QUAY_DOCKERCONFIGJSON=<docker-config-json> \
#   -n <your-namespace>
#
# Option 2: Using Sealed Secrets (for GitOps)
# -------------------------------------------
# 1. Create the secret YAML locally (don't commit!)
# 2. Seal it with kubeseal
# 3. Commit the sealed secret
#
# Option 3: Using External Secrets Operator
# -----------------------------------------
# Reference secrets from AWS Secrets Manager, HashiCorp Vault, etc.
# =============================================================================

---
# Secret 1: Llama Stack Secrets
# Required for the Llama Stack inference server
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-secrets  # Must match the name provided in the template
  labels:
    app.kubernetes.io/component: llama-stack
type: Opaque
stringData:
  # API key for vLLM server - required for inference
  VLLM_API_KEY: "<your-vllm-api-key>"
  
  # OpenAI API key - required for embeddings and inference
  OPENAI_API_KEY: "<your-openai-api-key>"

---
# Secret 2: Platform Credentials
# Required for the application (GitHub MCP Tool) and CI/CD pipelines (Tekton GitOps)
apiVersion: v1
kind: Secret
metadata:
  name: platform-credentials  # Must match the name provided in the template
  labels:
    app.kubernetes.io/component: platform
type: Opaque
stringData:
  # GitHub Personal Access Token with 'repo' scope
  # Used by:
  #   - Application: GitHub MCP Tool for issue creation and commenting
  #   - CI/CD: Tekton pipeline GitOps operations (pushing to gitops repo)
  # Create at: https://github.com/settings/tokens
  GITHUB_TOKEN: "<your-github-personal-access-token>"
  
  # GitLab PAT (only if using GitLab instead of GitHub)
  # Scopes needed: api, read_repository, write_repository
  # Note: The app's GitHub MCP Tool won't work with GitLab
  GITLAB_TOKEN: "<your-gitlab-pat>"
  
  # Pipelines as Code webhook secret (GitHub/GitLab)
  # Generate with: openssl rand -hex 20
  WEBHOOK_SECRET: "<your-webhook-secret>"
  
  # Docker config JSON for pushing images to registry
  # Format: '{"auths":{"quay.io":{"auth":"<base64-user:token>","email":"<email>"}}}'
  # The "auth" field is base64 encoded "username:password" or "username:token"
  # Generate auth with: echo -n "username:token" | base64
  QUAY_DOCKERCONFIGJSON: '{"auths":{"quay.io":{"auth":"","email":""}}}'
