# Service for Llama Stack Server
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/instance: ${{ values.name }}-llama-stack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ${{ values.name }}-llama-stack
  name: ${{ values.name }}-llama-stack
spec:
  ports:
    - port: 8321
      protocol: TCP
      targetPort: 8321
      name: http
  selector:
    app.kubernetes.io/instance: ${{ values.name }}-llama-stack

